# Generated by Django 5.0.1 on 2024-11-21 05:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personal_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('blood_group', models.CharField(blank=True, max_length=4, null=True)),
                ('current_address', models.CharField(blank=True, max_length=255, null=True)),
                ('permanent_address', models.CharField(blank=True, max_length=255, null=True)),
                ('employee_id', models.CharField(editable=False, max_length=10, unique=True)),
                ('position', models.CharField(blank=True, max_length=100, null=True)),
                ('job_profile', models.CharField(blank=True, max_length=100, null=True)),
                ('employee_type', models.CharField(blank=True, choices=[('Permanent', 'Permanent'), ('Contract', 'Contract')], max_length=10, null=True)),
                ('time_type', models.CharField(blank=True, choices=[('Full-Time', 'Full-Time'), ('Part-Time', 'Part-Time')], max_length=10, null=True)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('hire_date', models.DateField(blank=True, null=True)),
                ('length_of_service', models.CharField(blank=True, max_length=50, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('mobile_number', models.CharField(blank=True, max_length=15, null=True)),
                ('emergency_contact_person', models.CharField(blank=True, max_length=100, null=True)),
                ('emergency_contact_number', models.CharField(blank=True, max_length=15, null=True)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10, null=True)),
                ('country_of_birth', models.CharField(blank=True, max_length=100, null=True)),
                ('marital_status', models.CharField(blank=True, choices=[('Single', 'Single'), ('Married', 'Married')], max_length=10, null=True)),
                ('bank_account_name', models.CharField(blank=True, max_length=100, null=True)),
                ('bank_account_number', models.CharField(blank=True, max_length=20, null=True)),
                ('bank_account_ifsc_code', models.CharField(blank=True, max_length=11, null=True)),
                ('pf_uan_no', models.CharField(blank=True, max_length=20, null=True)),
                ('pf_no', models.CharField(blank=True, max_length=20, null=True)),
                ('pan_no', models.CharField(blank=True, max_length=10, null=True)),
                ('aadhar_number', models.CharField(blank=True, max_length=12, null=True)),
                ('reporting_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='details', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
