# Generated by Django 5.0.1 on 2024-11-21 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_managers_alter_user_groups_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='length_of_service',
            field=models.CharField(blank=True, editable=False, max_length=50, null=True),
        ),
    ]
