# Generated by Django 5.0.1 on 2024-11-29 03:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0009_alter_project_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="user",
        ),
        migrations.AddField(
            model_name="project",
            name="users",
            field=models.ManyToManyField(
                blank=True, related_name="projects", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
