# Generated by Django 5.0.1 on 2024-11-29 03:50

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0010_remove_project_user_project_users"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="timesheet",
            options={"ordering": ["-date", "project", "user"]},
        ),
        migrations.RenameField(
            model_name="timesheet",
            old_name="task_description",
            new_name="description",
        ),
        migrations.AlterUniqueTogether(
            name="timesheet",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="timesheet",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approved_timesheets",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="timesheet",
            name="approved_on",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="timesheet",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="timesheet",
            name="hours_spent",
            field=models.DecimalField(decimal_places=2, default=10, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="timesheet",
            name="is_approved",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="timesheet",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.RemoveField(
            model_name="timesheet",
            name="hours_worked",
        ),
        migrations.RemoveField(
            model_name="timesheet",
            name="is_billable",
        ),
    ]
